#!/usr/bin/env sh
set -e

# kill whole process group on exit
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

# test publisher
rm -rf scratch
mkdir scratch

mkdir scratch/logger-out
mkdir scratch/zig-irc-logs
git -C scratch/zig-irc-logs init

zig build run-publisher -- --logger-dir scratch/logger-out --repo scratch/zig-irc-logs &> scratch/publisher.out &
publisher_pid=$!

function addMsg() {
    num=$1
    timestamp=$2
    from=$3
    msg="$4"
    echo $timestamp > scratch/logger-out/${num}.partial
    echo "$from" >> scratch/logger-out/${num}.partial
    printf "$msg" >> scratch/logger-out/${num}.partial
    mv scratch/logger-out/${num}.partial scratch/logger-out/${num}
}

function waitWhile() {
    while "$@"; do
        sleep 0.1
    done
}
function waitUntil() {
    while true; do
        if "$@"; then
            break
        fi
        sleep 0.1
    done
}

addMsg 0 1622782862 somebody "hello there"
waitWhile test -e scratch/logger-out/0
test -e scratch/zig-irc-logs/2021/06-04.txt

# test a very old message
addMsg 0 1522992862 anotherbody "hi, how are you?"
waitUntil grep TimestampsMessedUp scratch/publisher.out

# start publisher again because it should have crashed
zig build run-publisher -- --logger-dir scratch/logger-out --repo scratch/zig-irc-logs &> scratch/publisher2.out &
publisher_pid=$!

rm -rf scratch/zig-irc-logs/2021
addMsg 0 1622782862 somebody "hello?"
waitWhile test -e scratch/logger-out/0
addMsg 1 1622782862 somebody "is anyone there?"
waitWhile test -e scratch/logger-out/1

echo --------------------------------------------------------------------------------
echo Success
